[versions]
junitVersion = "5.8.2"
jmhVersion = "1.32"
springbootVersion = "3.2.1"
jmhPluginVersion = '0.6.6'
dependencyManagementPluginVersion = "1.1.4"
graalvmNativePluginVersion = "0.9.28"
apiguardianVersion = '1.1.2'
jetbrainsAnnotationsVersion = '24.0.0'
licensePluginVersion = '0.16.2'
jacksonVersion = '2.16.0'

[libraries]
# https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api
junitJupiterApi = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junitVersion" }
# https://mvnrepository.com/artifact/org.openjdk.jmh/jmh-core
jmhCore = { module = "org.openjdk.jmh:jmh-core", version.ref = "jmhVersion" }
# https://mvnrepository.com/artifact/org.openjdk.jmh/jmh-generator-annprocess
jmhGeneratorAnnprocess = { module = "org.openjdk.jmh:jmh-generator-annprocess", version.ref = "jmhVersion" }
# https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter
springboot = { module = "org.springframework.boot:spring-boot-starter" }
# https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-test
springbootTest = { module = "org.springframework.boot:spring-boot-starter-test" }
# https://mvnrepository.com/artifact/org.apiguardian/apiguardian-api
apiguardian = { module = "org.apiguardian:apiguardian-api", version.ref = "apiguardianVersion" }
# https://mvnrepository.com/artifact/org.jetbrains/annotations
jetbrainsAnnotations = { module = "org.jetbrains:annotations", version.ref = "jetbrainsAnnotationsVersion" }
# https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-engine
junitJupiterEngine = { module = "org.junit.jupiter:junit-jupiter-engine" }
# https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-dependencies
springBootDependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "springbootVersion" }
# https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-web
springBootStarterWeb = { module = "org.springframework.boot:spring-boot-starter-web" }
# https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-core
jacksonCore = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jacksonVersion" }
# https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind
jacksonDatabind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jacksonVersion" }
# https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-annotations
jacksonAnnotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jacksonVersion" }

[bundles]
jmh = ["jmhCore", "jmhGeneratorAnnprocess"]
jackson = ["jacksonCore", "jacksonDatabind", "jacksonAnnotations"]

[plugins]
springboot = { id = "org.springframework.boot", version.ref = "springbootVersion" }
jmh = { id = "me.champeau.jmh", version.ref = "jmhPluginVersion" }
dependencyManagement = { id = "io.spring.dependency-management", version.ref = "dependencyManagementPluginVersion" }
graalvmNative = { id = "org.graalvm.buildtools.native", version.ref = "graalvmNativePluginVersion" }
java = { id = "java" }
idea = { id = "idea" }
checkstyle = { id = "checkstyle" }
license = { id = "com.benjaminsproule.license", version.ref = "licensePluginVersion" }
