#
# Copyright (c) 2024-2024, kaiyu.shan@outlook.com.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

server:
  port: ${port:31200}
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:31100
          jwk-set-uri: http://localhost:31100/oauth2/jwks
  application:
    name: log
  config:
    import: 'optional:consul:'
  cloud:
    consul:
      host: ${consul_ip:localhost}
      port: ${consul_port:8500}
      config:
        enabled: true
        default-context: ${spring.application.name}
        profile-separator: '-'
        format: YAML
        data-key: ${spring.application.name}
        watch:
          enabled: true
          delay: 1000
        prefixes: centaur
        acl-token: ${consul_token:e1da9899-6008-1999-07f6-f78c7d99715b}
      discovery:
        register: true
        instance-id: ${spring.application.name}
        service-name: ${spring.application.name}
        port: ${server.port}
        prefer-ip-address: true
        ip-address: ${spring.cloud.client.ip-address}
        acl-token: ${consul_token:e1da9899-6008-1999-07f6-f78c7d99715b}
centaur:
  resource:
    policies:
      - matcher: /operation/findById
        http-method: GET
        authority: message.read
      - matcher: /operation/submit
        http-method: POST
        authority: message.write
      - matcher: /system/submit
        http-method: POST
        authority: message.write
      - matcher: /actuator/**
        http-method: GET
        permit-all: true
