#
# Copyright (c) 2024-2024, kaiyu.shan@outlook.com.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

server:
  port: 31100

spring:
  application:
    name: authentication
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos_ip:localhost:8848}
        username: ${nacos_username:nacos}
        password: ${nacos_passwd:nacos}
        namespace: ${nacos_namespace:centaur}
        group: ${nacos_group:DEFAULT_GROUP}
        ip: 10.11.204.24
      config:
        server-addr: ${nacos_ip:localhost:8848}
        username: ${nacos_username:nacos}
        password: ${nacos_passwd:nacos}
        namespace: ${nacos_namespace:centaur}
        group: ${nacos_group:DEFAULT_GROUP}
        file-extension: yml
---
spring:
  config:
    import: nacos:${spring.application.name}-dev.yml
    activate:
      on-profile: dev
---
spring:
  config:
    import: nacos:${spring.application.name}-prod.yml
    activate:
      on-profile: prod
---
logging:
  level:
    org.springframework.security: debug
