server:
  port: 31300
spring:
  application:
    name: unique
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos_ip:localhost:8848}
        username: ${nacos_username:nacos}
        password: ${nacos_passwd:nacos}
        namespace: ${nacos_namespace:centaur}
        group: ${nacos_group:DEFAULT_GROUP}
      config:
        server-addr: ${nacos_ip:localhost:8848}
        username: ${nacos_username:nacos}
        password: ${nacos_passwd:nacos}
        namespace: ${nacos_namespace:centaur}
        group: ${nacos_group:DEFAULT_GROUP}
        file-extension: yml
---
spring:
  config:
    import: nacos:${spring.application.name}-dev.yml
    activate:
      on-profile: dev
---
spring:
  config:
    import: nacos:${spring.application.name}-prod.yml
    activate:
      on-profile: prod
---
